### ISSUE TITLE
How does one generate public.txt

### ISSUE THREAD

**Issue by Vanceagher** [Footsiefat/Minecraft-Server-Scanner#14]
Is there a script or something that can be used to generate a public.txt file so I can keep mine up to date?

**Comment by Annabxlla** [comment]
There shouldn't be a need to generate a public list, if anything just take the ip/ranges of big servers and put them in, (hypixel and such) but they should all already be accounted for.

**Comment by Footsiefat** [comment]
I don't think I have the script anymore, but what it essentially did is scrape server lists using requests and a `for` loop for each page
