### ISSUE TITLE
Any idea why I'm getting this error? I followed the setup step by step.

### ISSUE THREAD

**Issue by levfo** [Footsiefat/Minecraft-Server-Scanner#5]
Kind of new to programming, but not sure why I'm getting this error.
Any idea on how to fix? Thanks!
![image](https://user-images.githubusercontent.com/39710651/138942701-d59e8f34-be7a-4915-a60a-c3ef7cd1c051.png)

**Comment by Footsiefat** [comment]
Either python is too old or you need to try and install the python library suggested above @levfo
