### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Lojstr** [Footsiefat/Minecraft-Server-Scanner#7]
Can you add the MOTD information in the output txt file? EDIT: I added it.

**Comment by Lojstr** [comment]
and some info if that server is whitelisted

**Comment by Footsiefat** [comment]
Glad you got it figured out in the end, btw checking if it is whitelisted is whole another story since you need to actually join the server using a real minecraft account. If you wish for me to merge the change feel free to send a PR
